"""Sandbox kit: everything needed to test a converted .ktr safely.

Generated per mapping from the parsed IR — never against production:
- setup.md   : step-by-step PDI setup guide (connections, tables, data, run)
- setup.sql  : CREATE TABLE DDL inferred from the mapping's field metadata
- data_*.csv : synthetic test data typed from the real field definitions,
               deterministic (seeded) so test runs are reproducible
"""

import csv
import io
import random
from pathlib import Path

from pydantic import BaseModel

from pdi_migration.ir import FieldDef, Pipeline, Step

DB_STEP_TYPES = ("TableInput", "TableOutput", "StreamLookup")

# Informatica datatype -> portable ANSI-ish SQL type.
def sql_type(field: FieldDef) -> str:
    dt = field.datatype.lower()
    if dt in ("string", "nstring", "varchar"):
        return f"VARCHAR({field.precision or 255})"
    if dt == "text":
        return "TEXT"
    if dt == "decimal":
        return f"NUMERIC({field.precision or 18},{field.scale or 0})"
    if dt in ("double", "real"):
        return "DOUBLE PRECISION"
    if dt == "small integer":
        return "SMALLINT"
    if dt == "bigint":
        return "BIGINT"
    if dt == "integer":
        return "INTEGER"
    if dt in ("date/time", "timestamp", "date"):
        return "TIMESTAMP"
    return "VARCHAR(255)"  # unknown types stay loadable; refine by hand


_WORDS = ("north", "south", "east", "west", "central", "alpha", "beta",
          "gamma", "delta", "omega", "prime", "core", "edge", "apex")


def _synth_value(field: FieldDef, rng: random.Random, row: int) -> str:
    dt = field.datatype.lower()
    if dt == "decimal":
        scale = field.scale or 0
        whole_digits = max((field.precision or 10) - scale, 1)
        value = rng.uniform(0, 10 ** min(whole_digits, 6) - 1)
        return f"{value:.{scale}f}"
    if dt in ("double", "real"):
        return f"{rng.uniform(0, 100000):.4f}"
    if dt in ("integer", "small integer", "bigint"):
        return str(rng.randint(1, 32000))
    if dt in ("date/time", "timestamp", "date"):
        return (f"2026-{rng.randint(1, 12):02d}-{rng.randint(1, 28):02d} "
                f"{rng.randint(0, 23):02d}:{rng.randint(0, 59):02d}:00")
    # strings: readable, unique-ish, respecting precision
    text = f"{_WORDS[rng.randrange(len(_WORDS))]}_{row + 1}"
    return text[: field.precision or 255]


def generate_csv(fields: list[FieldDef], rows: int = 25, seed: int = 42) -> str:
    rng = random.Random(seed)
    out = io.StringIO()
    writer = csv.writer(out, lineterminator="\n")
    writer.writerow([f.name for f in fields])
    for row in range(rows):
        writer.writerow([_synth_value(f, rng, row) for f in fields])
    return out.getvalue()


def _upstream_fields(pipeline: Pipeline, step: Step) -> list[FieldDef]:
    """Best-effort columns for a field-less step (e.g. a Target): walk upstream
    until a step with fields is found."""
    current, seen = step, {step.name}
    while not current.fields:
        incoming = next((h for h in pipeline.hops if h.to_step == current.name), None)
        if incoming is None or incoming.from_step in seen:
            return []
        seen.add(incoming.from_step)
        current = pipeline.step(incoming.from_step) or current
        if current.name in seen and not current.fields and len(seen) > len(pipeline.steps):
            return []
    return current.fields


def _db_steps(pipeline: Pipeline) -> list[tuple[Step, list[FieldDef], str]]:
    """(step, columns, role) for every step that touches a database."""
    result = []
    for step in pipeline.steps:
        if step.pdi_type not in DB_STEP_TYPES:
            continue
        role = "read" if step.pdi_type in ("TableInput", "StreamLookup") else "write"
        result.append((step, step.fields or _upstream_fields(pipeline, step), role))
    return result


def build_ddl(pipeline: Pipeline) -> str:
    lines = [
        "-- Sandbox DDL generated by Migration Copilot — run against a SANDBOX database only.",
        f"-- Mapping: {pipeline.name}",
        "-- Column types are inferred from the PowerCenter export; verify before relying on them.",
        "",
    ]
    for step, columns, role in _db_steps(pipeline):
        if not columns:
            lines.append(f"-- {step.name} ({role}): no column metadata in the export — define by hand.")
            lines.append("")
            continue
        lines.append(f"-- {role.upper()}: {step.name}")
        cols = ",\n".join(f"    {f.name} {sql_type(f)}" for f in columns)
        lines.append(f"CREATE TABLE {step.name} (\n{cols}\n);")
        lines.append("")
    return "\n".join(lines)


def build_guide(pipeline: Pipeline) -> str:
    db_steps = _db_steps(pipeline)
    reads = [s.name for s, _, role in db_steps if role == "read"]
    writes = [s.name for s, _, role in db_steps if role == "write"]
    return f"""# Sandbox setup — {pipeline.name}

**⚠ Test in a sandbox database only. Never point the converted transformation at production.**

## 1. Create a PDI database connection

- Open `{pipeline.name}.ktr` in Spoon.
- View pane → *Database connections* → *New*; point it at your **sandbox** database
  (any test database works — PostgreSQL, H2, MySQL — it does not have to match the
  original source engine).
- The generated Table Input / Table Output steps have **empty connection
  placeholders**: open each step below and select your new connection.
  - Reads: {", ".join(reads) or "none"}
  - Writes: {", ".join(writes) or "none"}

## 2. Create the tables

Run `setup.sql` against the sandbox. Column types are inferred from the PowerCenter
export metadata; write-side tables are derived from upstream fields — verify them.

## 3. Load the synthetic test data

Each `data_<step>.csv` holds seeded synthetic rows shaped to the real field types
(same seed → same data, so runs are reproducible). Load them with your database's
import tool, or in Spoon with a quick *CSV file input → Table output* transformation.

## 4. Run and verify

- Run the transformation in Spoon and check the step metrics for errors.
- Review every step and expression flagged `review`/`manual` in the migration report —
  translated expressions carry their original Informatica source as comments.
- Spot-check output rows against the original mapping's behavior. (The runtime diff
  harness milestone will automate this comparison.)
"""


class SandboxKit(BaseModel):
    mapping: str
    guide: str
    ddl: str
    data: dict[str, str]  # filename -> csv content


def build_sandbox_kit(pipeline: Pipeline, rows: int = 25, seed: int = 42) -> SandboxKit:
    data = {
        f"data_{step.name}.csv": generate_csv(columns, rows=rows, seed=seed)
        for step, columns, role in _db_steps(pipeline)
        if role == "read" and columns
    }
    return SandboxKit(
        mapping=pipeline.name,
        guide=build_guide(pipeline),
        ddl=build_ddl(pipeline),
        data=data,
    )


def write_kit(kit: SandboxKit, out_dir: str | Path) -> Path:
    kit_dir = Path(out_dir) / "sandbox" / kit.mapping
    kit_dir.mkdir(parents=True, exist_ok=True)
    (kit_dir / "setup.md").write_text(kit.guide, encoding="utf-8")
    (kit_dir / "setup.sql").write_text(kit.ddl, encoding="utf-8")
    for name, content in kit.data.items():
        (kit_dir / name).write_text(content, encoding="utf-8")
    return kit_dir
