// Client-side migration report builder — markdown, from data already loaded.

export function buildMarkdownReport(source, result) {
  const { pipeline, report } = result
  const pct = report.total_steps ? Math.round((report.auto / report.total_steps) * 100) : 0
  const lines = [
    `# Migration report — ${pipeline.name}`,
    '',
    'Generated by Migration Copilot.',
    '',
    '## Source',
    '',
  ]
  if (source) {
    lines.push(
      `- Tool: ${source.tool} ${source.product_version ?? '(unknown version)'} (repository ${source.repository_version ?? '?'})`,
      `- Repository: ${source.repository_name ?? '—'} · Database: ${source.database_type ?? '—'} · Codepage: ${source.codepage ?? '—'}`,
      `- Exported: ${source.creation_date ?? '—'} · Folder(s): ${source.folders?.join(', ') || '—'}`,
      `- Contents: ${source.mappings} mappings, ${source.workflows} workflows, ${source.sessions} sessions, ${source.mapplets} mapplets`,
      '',
    )
    if (source.warnings?.length) {
      lines.push('### Pre-migration warnings', '')
      source.warnings.forEach((w) => lines.push(`- **[${w.level}]** ${w.text}`))
      lines.push('')
    }
  }
  if (result.score) {
    const s = result.score
    lines.push(
      '## Migration confidence',
      '',
      `**${s.score}/100 (grade ${s.grade}, static prediction)** — ${s.verdict}`,
      '',
    )
    s.factors.forEach((f) => lines.push(`- ${f.name}: ${f.score}/100 (${f.detail})`))
    lines.push('')
  }
  lines.push(
    '## Summary',
    '',
    `| Steps | Auto | Review | Manual | Expressions to translate |`,
    `| --- | --- | --- | --- | --- |`,
    `| ${report.total_steps} | ${report.auto} (${pct}%) | ${report.review} | ${report.manual} | ${report.untranslated_expressions} |`,
    '',
    '## Steps',
    '',
    '| Step | Source type | PDI step | Confidence | Notes |',
    '| --- | --- | --- | --- | --- |',
  )
  for (const s of pipeline.steps) {
    const notes = [
      ...s.notes,
      ...s.expressions.map((e) =>
        e.translated != null
          ? `translated: ${e.field} = ${e.translated}`
          : `TODO: ${e.field} = ${e.raw}`,
      ),
    ].join('; ').replaceAll('|', '\\|')
    lines.push(
      `| ${s.name} | ${s.source_type} | ${s.pdi_type ?? '—'} | ${s.confidence} | ${notes} |`,
    )
  }
  const expressions = pipeline.steps.flatMap((s) =>
    s.expressions.map((e) => ({ step: s.name, ...e })),
  )
  if (expressions.length) {
    lines.push('', '## Expressions', '')
    for (const e of expressions) {
      lines.push(`- **${e.step}.${e.field}**`)
      lines.push(`  - Informatica: \`${e.raw}\``)
      lines.push(
        e.translated != null
          ? `  - PDI (JavaScript): \`${e.translated}\`${e.notes ? ` — ${e.notes}` : ''}`
          : '  - Not translated yet.',
      )
    }
  }
  if (result.impact) {
    const { summary, entries } = result.impact
    lines.push('', '## Impact analysis', '')
    lines.push(`${summary.high} high · ${summary.medium} medium · ${summary.low} low · ${summary.none} none`, '')
    if (summary.top_risks.length) {
      lines.push('### Top risks', '')
      summary.top_risks.forEach((r) => lines.push(`- ${r}`))
      lines.push('')
    }
    for (const e of entries.filter((e) => e.impact === 'high' || e.impact === 'medium')) {
      lines.push(`### ${e.step} — ${e.source_type} → ${e.pdi_type ?? 'no mapping'} (impact: ${e.impact})`, '')
      e.differences.forEach((d) => lines.push(`- Difference: ${d}`))
      e.actions.forEach((a) => lines.push(`- Action: ${a}`))
      lines.push('')
    }
  }
  lines.push('', '---', '*Review every step marked `review` or `manual` before use. Test in a sandbox only.*', '')
  return lines.join('\n')
}
